import { Search, X } from 'lucide-react';
import { useEffect, useMemo, useRef, useState } from 'react';

type EmojiCategory = {
    name: string;
    icon: string;
    emojis: { emoji: string; name: string }[];
};

const EMOJI_CATEGORIES: EmojiCategory[] = [
    {
        name: 'Smileys & Emotion',
        icon: '😀',
        emojis: [
            { emoji: '😀', name: 'grinning face' },
            { emoji: '😃', name: 'grinning face with big eyes' },
            { emoji: '😄', name: 'grinning face with smiling eyes' },
            { emoji: '😁', name: 'beaming face with smiling eyes' },
            { emoji: '😆', name: 'grinning squinting face' },
            { emoji: '😅', name: 'grinning face with sweat' },
            { emoji: '🤣', name: 'rolling on the floor laughing' },
            { emoji: '😂', name: 'face with tears of joy' },
            { emoji: '🙂', name: 'slightly smiling face' },
            { emoji: '🙃', name: 'upside-down face' },
            { emoji: '🫠', name: 'melting face' },
            { emoji: '😉', name: 'winking face' },
            { emoji: '😊', name: 'smiling face with smiling eyes' },
            { emoji: '😇', name: 'smiling face with halo' },
            { emoji: '🥰', name: 'smiling face with hearts' },
            { emoji: '😍', name: 'heart eyes' },
            { emoji: '🤩', name: 'star-struck' },
            { emoji: '😘', name: 'face blowing a kiss' },
            { emoji: '😗', name: 'kissing face' },
            { emoji: '😚', name: 'kissing face with closed eyes' },
            { emoji: '😙', name: 'kissing face with smiling eyes' },
            { emoji: '😋', name: 'face savoring food' },
            { emoji: '😛', name: 'face with tongue' },
            { emoji: '😜', name: 'winking face with tongue' },
            { emoji: '🤪', name: 'zany face' },
            { emoji: '😝', name: 'squinting face with tongue' },
            { emoji: '🤑', name: 'money-mouth face' },
            { emoji: '🤗', name: 'smiling face with open hands' },
            { emoji: '🤭', name: 'face with hand over mouth' },
            { emoji: '🫢', name: 'face with open eyes and hand over mouth' },
            { emoji: '🫣', name: 'face with peeking eye' },
            { emoji: '🤫', name: 'shushing face' },
            { emoji: '🤔', name: 'thinking face' },
            { emoji: '🫡', name: 'saluting face' },
            { emoji: '🤐', name: 'zipper-mouth face' },
            { emoji: '🤨', name: 'face with raised eyebrow' },
            { emoji: '😐', name: 'neutral face' },
            { emoji: '😑', name: 'expressionless face' },
            { emoji: '😶', name: 'face without mouth' },
            { emoji: '🫥', name: 'dotted line face' },
            { emoji: '😏', name: 'smirking face' },
            { emoji: '😒', name: 'unamused face' },
            { emoji: '🙄', name: 'face with rolling eyes' },
            { emoji: '😬', name: 'grimacing face' },
            { emoji: '😮‍💨', name: 'face exhaling' },
            { emoji: '🤥', name: 'lying face' },
            { emoji: '😌', name: 'relieved face' },
            { emoji: '😔', name: 'pensive face' },
            { emoji: '😪', name: 'sleepy face' },
            { emoji: '🤤', name: 'drooling face' },
            { emoji: '😴', name: 'sleeping face' },
            { emoji: '😷', name: 'face with medical mask' },
            { emoji: '🤒', name: 'face with thermometer' },
            { emoji: '🤕', name: 'face with head-bandage' },
            { emoji: '🤢', name: 'nauseated face' },
            { emoji: '🤮', name: 'face vomiting' },
            { emoji: '🤧', name: 'sneezing face' },
            { emoji: '🥵', name: 'hot face' },
            { emoji: '🥶', name: 'cold face' },
            { emoji: '🥴', name: 'woozy face' },
            { emoji: '😵', name: 'dizzy face' },
            { emoji: '😵‍💫', name: 'face with spiral eyes' },
            { emoji: '🤯', name: 'exploding head' },
            { emoji: '🤠', name: 'cowboy hat face' },
            { emoji: '🥳', name: 'partying face' },
            { emoji: '🥸', name: 'disguised face' },
            { emoji: '😎', name: 'smiling face with sunglasses' },
            { emoji: '🤓', name: 'nerd face' },
            { emoji: '🧐', name: 'face with monocle' },
            { emoji: '😕', name: 'confused face' },
            { emoji: '🫤', name: 'face with diagonal mouth' },
            { emoji: '😟', name: 'worried face' },
            { emoji: '🙁', name: 'slightly frowning face' },
            { emoji: '😮', name: 'face with open mouth' },
            { emoji: '😯', name: 'hushed face' },
            { emoji: '😲', name: 'astonished face' },
            { emoji: '😳', name: 'flushed face' },
            { emoji: '🥺', name: 'pleading face' },
            { emoji: '🥹', name: 'face holding back tears' },
            { emoji: '😦', name: 'frowning face with open mouth' },
            { emoji: '😨', name: 'fearful face' },
            { emoji: '😰', name: 'anxious face with sweat' },
            { emoji: '😥', name: 'sad but relieved face' },
            { emoji: '😢', name: 'crying face' },
            { emoji: '😭', name: 'loudly crying face' },
            { emoji: '😱', name: 'face screaming in fear' },
            { emoji: '😖', name: 'confounded face' },
            { emoji: '😣', name: 'persevering face' },
            { emoji: '😞', name: 'disappointed face' },
            { emoji: '😓', name: 'downcast face with sweat' },
            { emoji: '😩', name: 'weary face' },
            { emoji: '😫', name: 'tired face' },
            { emoji: '🥱', name: 'yawning face' },
            { emoji: '😤', name: 'face with steam from nose' },
            { emoji: '😡', name: 'pouting face' },
            { emoji: '😠', name: 'angry face' },
            { emoji: '🤬', name: 'face with symbols on mouth' },
            { emoji: '😈', name: 'smiling face with horns' },
            { emoji: '👿', name: 'angry face with horns' },
            { emoji: '💀', name: 'skull' },
            { emoji: '☠️', name: 'skull and crossbones' },
            { emoji: '💩', name: 'pile of poo' },
            { emoji: '🤡', name: 'clown face' },
            { emoji: '👹', name: 'ogre' },
            { emoji: '👺', name: 'goblin' },
            { emoji: '👻', name: 'ghost' },
            { emoji: '👽', name: 'alien' },
            { emoji: '👾', name: 'alien monster' },
            { emoji: '🤖', name: 'robot' },
        ],
    },
    {
        name: 'Gestures & People',
        icon: '👋',
        emojis: [
            { emoji: '👋', name: 'waving hand' },
            { emoji: '🤚', name: 'raised back of hand' },
            { emoji: '🖐️', name: 'hand with fingers splayed' },
            { emoji: '✋', name: 'raised hand' },
            { emoji: '🖖', name: 'vulcan salute' },
            { emoji: '🫱', name: 'rightwards hand' },
            { emoji: '🫲', name: 'leftwards hand' },
            { emoji: '🫳', name: 'palm down hand' },
            { emoji: '🫴', name: 'palm up hand' },
            { emoji: '👌', name: 'OK hand' },
            { emoji: '🤌', name: 'pinched fingers' },
            { emoji: '🤏', name: 'pinching hand' },
            { emoji: '✌️', name: 'victory hand' },
            { emoji: '🤞', name: 'crossed fingers' },
            { emoji: '🫰', name: 'hand with index finger and thumb crossed' },
            { emoji: '🤟', name: 'love-you gesture' },
            { emoji: '🤘', name: 'sign of the horns' },
            { emoji: '🤙', name: 'call me hand' },
            { emoji: '👈', name: 'backhand index pointing left' },
            { emoji: '👉', name: 'backhand index pointing right' },
            { emoji: '👆', name: 'backhand index pointing up' },
            { emoji: '🖕', name: 'middle finger' },
            { emoji: '👇', name: 'backhand index pointing down' },
            { emoji: '☝️', name: 'index pointing up' },
            { emoji: '🫵', name: 'index pointing at the viewer' },
            { emoji: '👍', name: 'thumbs up' },
            { emoji: '👎', name: 'thumbs down' },
            { emoji: '✊', name: 'raised fist' },
            { emoji: '👊', name: 'oncoming fist' },
            { emoji: '🤛', name: 'left-facing fist' },
            { emoji: '🤜', name: 'right-facing fist' },
            { emoji: '👏', name: 'clapping hands' },
            { emoji: '🙌', name: 'raising hands' },
            { emoji: '🫶', name: 'heart hands' },
            { emoji: '👐', name: 'open hands' },
            { emoji: '🤲', name: 'palms up together' },
            { emoji: '🤝', name: 'handshake' },
            { emoji: '🙏', name: 'folded hands' },
            { emoji: '✍️', name: 'writing hand' },
            { emoji: '💅', name: 'nail polish' },
            { emoji: '🤳', name: 'selfie' },
            { emoji: '💪', name: 'flexed biceps' },
            { emoji: '🦾', name: 'mechanical arm' },
            { emoji: '🦿', name: 'mechanical leg' },
            { emoji: '🦵', name: 'leg' },
            { emoji: '🦶', name: 'foot' },
            { emoji: '👂', name: 'ear' },
            { emoji: '👃', name: 'nose' },
            { emoji: '🧠', name: 'brain' },
            { emoji: '🫀', name: 'anatomical heart' },
            { emoji: '🫁', name: 'lungs' },
            { emoji: '🦷', name: 'tooth' },
            { emoji: '🦴', name: 'bone' },
            { emoji: '👀', name: 'eyes' },
            { emoji: '👁️', name: 'eye' },
            { emoji: '👅', name: 'tongue' },
            { emoji: '👄', name: 'mouth' },
            { emoji: '🫦', name: 'biting lip' },
            { emoji: '💋', name: 'kiss mark' },
            { emoji: '❤️', name: 'red heart' },
            { emoji: '🩷', name: 'pink heart' },
            { emoji: '🧡', name: 'orange heart' },
            { emoji: '💛', name: 'yellow heart' },
            { emoji: '💚', name: 'green heart' },
            { emoji: '💙', name: 'blue heart' },
            { emoji: '🩵', name: 'light blue heart' },
            { emoji: '💜', name: 'purple heart' },
            { emoji: '🤎', name: 'brown heart' },
            { emoji: '🖤', name: 'black heart' },
            { emoji: '🩶', name: 'grey heart' },
            { emoji: '🤍', name: 'white heart' },
            { emoji: '💔', name: 'broken heart' },
            { emoji: '❤️‍🔥', name: 'heart on fire' },
            { emoji: '❤️‍🩹', name: 'mending heart' },
            { emoji: '💖', name: 'sparkling heart' },
            { emoji: '💗', name: 'growing heart' },
            { emoji: '💓', name: 'beating heart' },
            { emoji: '💞', name: 'revolving hearts' },
            { emoji: '💕', name: 'two hearts' },
            { emoji: '💬', name: 'speech balloon' },
            { emoji: '💭', name: 'thought balloon' },
            { emoji: '✨', name: 'sparkles' },
            { emoji: '🔥', name: 'fire' },
            { emoji: '💥', name: 'collision' },
            { emoji: '💯', name: 'hundred points' },
        ],
    },
    {
        name: 'Animals & Nature',
        icon: '🐱',
        emojis: [
            { emoji: '🐶', name: 'dog face' },
            { emoji: '🐱', name: 'cat face' },
            { emoji: '🐭', name: 'mouse face' },
            { emoji: '🐹', name: 'hamster face' },
            { emoji: '🐰', name: 'rabbit face' },
            { emoji: '🦊', name: 'fox' },
            { emoji: '🐻', name: 'bear' },
            { emoji: '🐼', name: 'panda' },
            { emoji: '🐻‍❄️', name: 'polar bear' },
            { emoji: '🐨', name: 'koala' },
            { emoji: '🐯', name: 'tiger face' },
            { emoji: '🦁', name: 'lion' },
            { emoji: '🐮', name: 'cow face' },
            { emoji: '🐷', name: 'pig face' },
            { emoji: '🐽', name: 'pig nose' },
            { emoji: '🐸', name: 'frog' },
            { emoji: '🐵', name: 'monkey face' },
            { emoji: '🙈', name: 'see-no-evil monkey' },
            { emoji: '🙉', name: 'hear-no-evil monkey' },
            { emoji: '🙊', name: 'speak-no-evil monkey' },
            { emoji: '🐒', name: 'monkey' },
            { emoji: '🐔', name: 'chicken' },
            { emoji: '🐧', name: 'penguin' },
            { emoji: '🐦', name: 'bird' },
            { emoji: '🐤', name: 'baby chick' },
            { emoji: '🐣', name: 'hatching chick' },
            { emoji: '🐥', name: 'front-facing baby chick' },
            { emoji: '🦆', name: 'duck' },
            { emoji: '🦅', name: 'eagle' },
            { emoji: '🦉', name: 'owl' },
            { emoji: '🦇', name: 'bat' },
            { emoji: '🐺', name: 'wolf' },
            { emoji: '🐗', name: 'boar' },
            { emoji: '🐴', name: 'horse face' },
            { emoji: '🦄', name: 'unicorn' },
            { emoji: '🐝', name: 'honeybee' },
            { emoji: '🪱', name: 'worm' },
            { emoji: '🐛', name: 'bug' },
            { emoji: '🦋', name: 'butterfly' },
            { emoji: '🐌', name: 'snail' },
            { emoji: '🐞', name: 'lady beetle' },
            { emoji: '🐜', name: 'ant' },
            { emoji: '🪰', name: 'fly' },
            { emoji: '🪲', name: 'beetle' },
            { emoji: '🪳', name: 'cockroach' },
            { emoji: '🦟', name: 'mosquito' },
            { emoji: '🦗', name: 'cricket' },
            { emoji: '🕷️', name: 'spider' },
            { emoji: '🦂', name: 'scorpion' },
            { emoji: '🐢', name: 'turtle' },
            { emoji: '🐍', name: 'snake' },
            { emoji: '🦎', name: 'lizard' },
            { emoji: '🦖', name: 'T-Rex' },
            { emoji: '🦕', name: 'sauropod' },
            { emoji: '🐙', name: 'octopus' },
            { emoji: '🦑', name: 'squid' },
            { emoji: '🦐', name: 'shrimp' },
            { emoji: '🦞', name: 'lobster' },
            { emoji: '🦀', name: 'crab' },
            { emoji: '🐡', name: 'blowfish' },
            { emoji: '🐠', name: 'tropical fish' },
            { emoji: '🐟', name: 'fish' },
            { emoji: '🐬', name: 'dolphin' },
            { emoji: '🐳', name: 'spouting whale' },
            { emoji: '🐋', name: 'whale' },
            { emoji: '🦈', name: 'shark' },
            { emoji: '🐊', name: 'crocodile' },
            { emoji: '🐅', name: 'tiger' },
            { emoji: '🐆', name: 'leopard' },
            { emoji: '🦓', name: 'zebra' },
            { emoji: '🦍', name: 'gorilla' },
            { emoji: '🦧', name: 'orangutan' },
            { emoji: '🐘', name: 'elephant' },
            { emoji: '🦛', name: 'hippopotamus' },
            { emoji: '🦏', name: 'rhinoceros' },
            { emoji: '🐪', name: 'camel' },
            { emoji: '🐫', name: 'two-hump camel' },
            { emoji: '🦒', name: 'giraffe' },
            { emoji: '🦘', name: 'kangaroo' },
            { emoji: '🦬', name: 'bison' },
            { emoji: '🐃', name: 'water buffalo' },
            { emoji: '🐂', name: 'ox' },
            { emoji: '🐄', name: 'cow' },
            { emoji: '🐎', name: 'horse' },
            { emoji: '🐖', name: 'pig' },
            { emoji: '🐏', name: 'ram' },
            { emoji: '🐑', name: 'ewe' },
            { emoji: '🦙', name: 'llama' },
            { emoji: '🐐', name: 'goat' },
            { emoji: '🦌', name: 'deer' },
            { emoji: '🐕', name: 'dog' },
            { emoji: '🐩', name: 'poodle' },
            { emoji: '🦮', name: 'guide dog' },
            { emoji: '🐈', name: 'cat' },
            { emoji: '🐓', name: 'rooster' },
            { emoji: '🦃', name: 'turkey' },
            { emoji: '🦚', name: 'peacock' },
            { emoji: '🦜', name: 'parrot' },
            { emoji: '🦢', name: 'swan' },
            { emoji: '🦩', name: 'flamingo' },
            { emoji: '🕊️', name: 'dove' },
            { emoji: '🐇', name: 'rabbit' },
            { emoji: '🦝', name: 'raccoon' },
            { emoji: '🦨', name: 'skunk' },
            { emoji: '🦡', name: 'badger' },
            { emoji: '🦫', name: 'beaver' },
            { emoji: '🦦', name: 'otter' },
            { emoji: '🦥', name: 'sloth' },
            { emoji: '🐁', name: 'mouse' },
            { emoji: '🐀', name: 'rat' },
            { emoji: '🐿️', name: 'chipmunk' },
            { emoji: '🦔', name: 'hedgehog' },
            { emoji: '🌸', name: 'cherry blossom' },
            { emoji: '💮', name: 'white flower' },
            { emoji: '🏵️', name: 'rosette' },
            { emoji: '🌹', name: 'rose' },
            { emoji: '🥀', name: 'wilted flower' },
            { emoji: '🌺', name: 'hibiscus' },
            { emoji: '🌻', name: 'sunflower' },
            { emoji: '🌼', name: 'blossom' },
            { emoji: '🌷', name: 'tulip' },
            { emoji: '🌱', name: 'seedling' },
            { emoji: '🪴', name: 'potted plant' },
            { emoji: '🌲', name: 'evergreen tree' },
            { emoji: '🌳', name: 'deciduous tree' },
            { emoji: '🌴', name: 'palm tree' },
            { emoji: '🌵', name: 'cactus' },
            { emoji: '🌾', name: 'sheaf of rice' },
            { emoji: '🌿', name: 'herb' },
            { emoji: '☘️', name: 'shamrock' },
            { emoji: '🍀', name: 'four leaf clover' },
            { emoji: '🍁', name: 'maple leaf' },
            { emoji: '🍂', name: 'fallen leaf' },
            { emoji: '🍃', name: 'leaf fluttering in wind' },
        ],
    },
    {
        name: 'Food & Drink',
        icon: '🍕',
        emojis: [
            { emoji: '🍏', name: 'green apple' },
            { emoji: '🍎', name: 'red apple' },
            { emoji: '🍐', name: 'pear' },
            { emoji: '🍊', name: 'tangerine' },
            { emoji: '🍋', name: 'lemon' },
            { emoji: '🍌', name: 'banana' },
            { emoji: '🍉', name: 'watermelon' },
            { emoji: '🍇', name: 'grapes' },
            { emoji: '🍓', name: 'strawberry' },
            { emoji: '🫐', name: 'blueberries' },
            { emoji: '🍈', name: 'melon' },
            { emoji: '🍒', name: 'cherries' },
            { emoji: '🍑', name: 'peach' },
            { emoji: '🥭', name: 'mango' },
            { emoji: '🍍', name: 'pineapple' },
            { emoji: '🥥', name: 'coconut' },
            { emoji: '🥝', name: 'kiwi fruit' },
            { emoji: '🍅', name: 'tomato' },
            { emoji: '🍆', name: 'eggplant' },
            { emoji: '🥑', name: 'avocado' },
            { emoji: '🥦', name: 'broccoli' },
            { emoji: '🥬', name: 'leafy green' },
            { emoji: '🥒', name: 'cucumber' },
            { emoji: '🌶️', name: 'hot pepper' },
            { emoji: '🫑', name: 'bell pepper' },
            { emoji: '🌽', name: 'ear of corn' },
            { emoji: '🥕', name: 'carrot' },
            { emoji: '🫒', name: 'olive' },
            { emoji: '🧄', name: 'garlic' },
            { emoji: '🧅', name: 'onion' },
            { emoji: '🥔', name: 'potato' },
            { emoji: '🍠', name: 'roasted sweet potato' },
            { emoji: '🥐', name: 'croissant' },
            { emoji: '🥯', name: 'bagel' },
            { emoji: '🍞', name: 'bread' },
            { emoji: '🥖', name: 'baguette bread' },
            { emoji: '🥨', name: 'pretzel' },
            { emoji: '🧀', name: 'cheese wedge' },
            { emoji: '🥚', name: 'egg' },
            { emoji: '🍳', name: 'cooking' },
            { emoji: '🧈', name: 'butter' },
            { emoji: '🥞', name: 'pancakes' },
            { emoji: '🧇', name: 'waffle' },
            { emoji: '🥓', name: 'bacon' },
            { emoji: '🥩', name: 'cut of meat' },
            { emoji: '🍗', name: 'poultry leg' },
            { emoji: '🍖', name: 'meat on bone' },
            { emoji: '🌭', name: 'hot dog' },
            { emoji: '🍔', name: 'hamburger' },
            { emoji: '🍟', name: 'french fries' },
            { emoji: '🍕', name: 'pizza' },
            { emoji: '🫓', name: 'flatbread' },
            { emoji: '🥪', name: 'sandwich' },
            { emoji: '🥙', name: 'stuffed flatbread' },
            { emoji: '🧆', name: 'falafel' },
            { emoji: '🌮', name: 'taco' },
            { emoji: '🌯', name: 'burrito' },
            { emoji: '🫔', name: 'tamale' },
            { emoji: '🥗', name: 'green salad' },
            { emoji: '🥘', name: 'shallow pan of food' },
            { emoji: '🫕', name: 'fondue' },
            { emoji: '🥣', name: 'bowl with spoon' },
            { emoji: '🍲', name: 'pot of food' },
            { emoji: '🍜', name: 'steaming bowl' },
            { emoji: '🍝', name: 'spaghetti' },
            { emoji: '🥟', name: 'dumpling' },
            { emoji: '🍣', name: 'sushi' },
            { emoji: '🍱', name: 'bento box' },
            { emoji: '🍤', name: 'fried shrimp' },
            { emoji: '🍙', name: 'rice ball' },
            { emoji: '🍚', name: 'cooked rice' },
            { emoji: '🍘', name: 'rice cracker' },
            { emoji: '🍥', name: 'fish cake with swirl' },
            { emoji: '🥠', name: 'fortune cookie' },
            { emoji: '🥮', name: 'moon cake' },
            { emoji: '🍢', name: 'oden' },
            { emoji: '🍡', name: 'dango' },
            { emoji: '🍧', name: 'shaved ice' },
            { emoji: '🍨', name: 'ice cream' },
            { emoji: '🍦', name: 'soft ice cream' },
            { emoji: '🥧', name: 'pie' },
            { emoji: '🧁', name: 'cupcake' },
            { emoji: '🍰', name: 'shortcake' },
            { emoji: '🎂', name: 'birthday cake' },
            { emoji: '🍮', name: 'custard' },
            { emoji: '🍭', name: 'lollipop' },
            { emoji: '🍬', name: 'candy' },
            { emoji: '🍫', name: 'chocolate bar' },
            { emoji: '🍿', name: 'popcorn' },
            { emoji: '🍩', name: 'doughnut' },
            { emoji: '🍪', name: 'cookie' },
            { emoji: '🌰', name: 'chestnut' },
            { emoji: '🥜', name: 'peanuts' },
            { emoji: '🍯', name: 'honey pot' },
            { emoji: '🥛', name: 'glass of milk' },
            { emoji: '🍼', name: 'baby bottle' },
            { emoji: '☕', name: 'hot beverage' },
            { emoji: '🫖', name: 'teapot' },
            { emoji: '🍵', name: 'teacup without handle' },
            { emoji: '🧃', name: 'beverage box' },
            { emoji: '🥤', name: 'cup with straw' },
            { emoji: '🧋', name: 'bubble tea' },
            { emoji: '🫙', name: 'jar' },
            { emoji: '🍺', name: 'beer mug' },
            { emoji: '🍻', name: 'clinking beer mugs' },
            { emoji: '🥂', name: 'clinking glasses' },
            { emoji: '🍷', name: 'wine glass' },
            { emoji: '🥃', name: 'tumbler glass' },
            { emoji: '🍸', name: 'cocktail glass' },
            { emoji: '🍹', name: 'tropical drink' },
            { emoji: '🍾', name: 'bottle with popping cork' },
            { emoji: '🧊', name: 'ice' },
        ],
    },
    {
        name: 'Activities & Objects',
        icon: '⚽',
        emojis: [
            { emoji: '⚽', name: 'soccer ball' },
            { emoji: '🏀', name: 'basketball' },
            { emoji: '🏈', name: 'american football' },
            { emoji: '⚾', name: 'baseball' },
            { emoji: '🥎', name: 'softball' },
            { emoji: '🎾', name: 'tennis' },
            { emoji: '🏐', name: 'volleyball' },
            { emoji: '🏉', name: 'rugby football' },
            { emoji: '🥏', name: 'flying disc' },
            { emoji: '🎱', name: 'pool 8 ball' },
            { emoji: '🪀', name: 'yo-yo' },
            { emoji: '🏓', name: 'ping pong' },
            { emoji: '🏸', name: 'badminton' },
            { emoji: '🏒', name: 'ice hockey' },
            { emoji: '🏑', name: 'field hockey' },
            { emoji: '🥍', name: 'lacrosse' },
            { emoji: '🏏', name: 'cricket game' },
            { emoji: '🪃', name: 'boomerang' },
            { emoji: '🥅', name: 'goal net' },
            { emoji: '⛳', name: 'flag in hole' },
            { emoji: '🪁', name: 'kite' },
            { emoji: '🏹', name: 'bow and arrow' },
            { emoji: '🎣', name: 'fishing pole' },
            { emoji: '🤿', name: 'diving mask' },
            { emoji: '🥊', name: 'boxing glove' },
            { emoji: '🥋', name: 'martial arts uniform' },
            { emoji: '🎽', name: 'running shirt' },
            { emoji: '🛹', name: 'skateboard' },
            { emoji: '🛼', name: 'roller skate' },
            { emoji: '🛷', name: 'sled' },
            { emoji: '⛸️', name: 'ice skate' },
            { emoji: '🥌', name: 'curling stone' },
            { emoji: '🎿', name: 'skis' },
            { emoji: '⛷️', name: 'skier' },
            { emoji: '🏂', name: 'snowboarder' },
            { emoji: '🪂', name: 'parachute' },
            { emoji: '🏋️', name: 'person lifting weights' },
            { emoji: '🤼', name: 'people wrestling' },
            { emoji: '🤸', name: 'person cartwheeling' },
            { emoji: '🧗', name: 'person climbing' },
            { emoji: '🚴', name: 'person biking' },
            { emoji: '🏆', name: 'trophy' },
            { emoji: '🥇', name: '1st place medal' },
            { emoji: '🥈', name: '2nd place medal' },
            { emoji: '🥉', name: '3rd place medal' },
            { emoji: '🏅', name: 'sports medal' },
            { emoji: '🎖️', name: 'military medal' },
            { emoji: '🏵️', name: 'rosette' },
            { emoji: '🎗️', name: 'reminder ribbon' },
            { emoji: '🎫', name: 'ticket' },
            { emoji: '🎟️', name: 'admission tickets' },
            { emoji: '🎪', name: 'circus tent' },
            { emoji: '🤹', name: 'person juggling' },
            { emoji: '🎭', name: 'performing arts' },
            { emoji: '🎨', name: 'artist palette' },
            { emoji: '🎬', name: 'clapper board' },
            { emoji: '🎤', name: 'microphone' },
            { emoji: '🎧', name: 'headphone' },
            { emoji: '🎼', name: 'musical score' },
            { emoji: '🎵', name: 'musical note' },
            { emoji: '🎶', name: 'musical notes' },
            { emoji: '🥁', name: 'drum' },
            { emoji: '🎷', name: 'saxophone' },
            { emoji: '🎺', name: 'trumpet' },
            { emoji: '🎸', name: 'guitar' },
            { emoji: '🪕', name: 'banjo' },
            { emoji: '🎻', name: 'violin' },
            { emoji: '🎲', name: 'game die' },
            { emoji: '♟️', name: 'chess pawn' },
            { emoji: '🎯', name: 'direct hit' },
            { emoji: '🎳', name: 'bowling' },
            { emoji: '🎮', name: 'video game' },
            { emoji: '🎰', name: 'slot machine' },
            { emoji: '🧩', name: 'puzzle piece' },
            { emoji: '🧸', name: 'teddy bear' },
            { emoji: '🪅', name: 'piñata' },
            { emoji: '🪩', name: 'mirror ball' },
            { emoji: '🎁', name: 'wrapped gift' },
            { emoji: '🎈', name: 'balloon' },
            { emoji: '🎉', name: 'party popper' },
            { emoji: '🎊', name: 'confetti ball' },
            { emoji: '🪄', name: 'magic wand' },
        ],
    },
    {
        name: 'Tech & Symbols',
        icon: '💡',
        emojis: [
            { emoji: '💡', name: 'light bulb' },
            { emoji: '🔦', name: 'flashlight' },
            { emoji: '🕯️', name: 'candle' },
            { emoji: '📱', name: 'mobile phone' },
            { emoji: '💻', name: 'laptop' },
            { emoji: '🖥️', name: 'desktop computer' },
            { emoji: '🖨️', name: 'printer' },
            { emoji: '⌨️', name: 'keyboard' },
            { emoji: '🖱️', name: 'computer mouse' },
            { emoji: '💽', name: 'computer disk' },
            { emoji: '💾', name: 'floppy disk' },
            { emoji: '💿', name: 'optical disk' },
            { emoji: '📀', name: 'dvd' },
            { emoji: '📷', name: 'camera' },
            { emoji: '📸', name: 'camera with flash' },
            { emoji: '📹', name: 'video camera' },
            { emoji: '🎥', name: 'movie camera' },
            { emoji: '📽️', name: 'film projector' },
            { emoji: '📞', name: 'telephone receiver' },
            { emoji: '☎️', name: 'telephone' },
            { emoji: '📟', name: 'pager' },
            { emoji: '📠', name: 'fax machine' },
            { emoji: '📺', name: 'television' },
            { emoji: '📻', name: 'radio' },
            { emoji: '🧭', name: 'compass' },
            { emoji: '⏱️', name: 'stopwatch' },
            { emoji: '⏲️', name: 'timer clock' },
            { emoji: '⏰', name: 'alarm clock' },
            { emoji: '🕰️', name: 'mantelpiece clock' },
            { emoji: '⌛', name: 'hourglass done' },
            { emoji: '⏳', name: 'hourglass not done' },
            { emoji: '📡', name: 'satellite antenna' },
            { emoji: '🔋', name: 'battery' },
            { emoji: '🪫', name: 'low battery' },
            { emoji: '🔌', name: 'electric plug' },
            { emoji: '🧯', name: 'fire extinguisher' },
            { emoji: '🛢️', name: 'oil drum' },
            { emoji: '💸', name: 'money with wings' },
            { emoji: '💵', name: 'dollar banknote' },
            { emoji: '💴', name: 'yen banknote' },
            { emoji: '💶', name: 'euro banknote' },
            { emoji: '💷', name: 'pound banknote' },
            { emoji: '🪙', name: 'coin' },
            { emoji: '💰', name: 'money bag' },
            { emoji: '💳', name: 'credit card' },
            { emoji: '💎', name: 'gem stone' },
            { emoji: '⚖️', name: 'balance scale' },
            { emoji: '🪜', name: 'ladder' },
            { emoji: '🧰', name: 'toolbox' },
            { emoji: '🪛', name: 'screwdriver' },
            { emoji: '🔧', name: 'wrench' },
            { emoji: '🔨', name: 'hammer' },
            { emoji: '⚒️', name: 'hammer and pick' },
            { emoji: '🛠️', name: 'hammer and wrench' },
            { emoji: '⛏️', name: 'pick' },
            { emoji: '🪚', name: 'carpentry saw' },
            { emoji: '⚙️', name: 'gear' },
            { emoji: '🪤', name: 'mouse trap' },
            { emoji: '🧱', name: 'brick' },
            { emoji: '⛓️', name: 'chains' },
            { emoji: '🧲', name: 'magnet' },
            { emoji: '🔫', name: 'water pistol' },
            { emoji: '💣', name: 'bomb' },
            { emoji: '🧨', name: 'firecracker' },
            { emoji: '🪓', name: 'axe' },
            { emoji: '🔪', name: 'kitchen knife' },
            { emoji: '🗡️', name: 'dagger' },
            { emoji: '⚔️', name: 'crossed swords' },
            { emoji: '🛡️', name: 'shield' },
            { emoji: '🚬', name: 'cigarette' },
            { emoji: '⚰️', name: 'coffin' },
            { emoji: '🪦', name: 'headstone' },
            { emoji: '⚱️', name: 'funeral urn' },
            { emoji: '🏺', name: 'amphora' },
            { emoji: '🔮', name: 'crystal ball' },
            { emoji: '📿', name: 'prayer beads' },
            { emoji: '🧿', name: 'nazar amulet' },
            { emoji: '💈', name: 'barber pole' },
            { emoji: '⚗️', name: 'alembic' },
            { emoji: '🔭', name: 'telescope' },
            { emoji: '🔬', name: 'microscope' },
            { emoji: '🕳️', name: 'hole' },
            { emoji: '🩹', name: 'adhesive bandage' },
            { emoji: '🩺', name: 'stethoscope' },
            { emoji: '💊', name: 'pill' },
            { emoji: '💉', name: 'syringe' },
            { emoji: '🩸', name: 'drop of blood' },
            { emoji: '🧬', name: 'dna' },
            { emoji: '🦠', name: 'microbe' },
            { emoji: '🧫', name: 'petri dish' },
            { emoji: '🧪', name: 'test tube' },
            { emoji: '🌡️', name: 'thermometer' },
            { emoji: '🧹', name: 'broom' },
            { emoji: '🪠', name: 'plunger' },
            { emoji: '🧺', name: 'basket' },
            { emoji: '🧻', name: 'roll of paper' },
            { emoji: '🧼', name: 'soap' },
            { emoji: '🫧', name: 'bubbles' },
            { emoji: '🪥', name: 'toothbrush' },
            { emoji: '🧽', name: 'sponge' },
            { emoji: '🔑', name: 'key' },
            { emoji: '🗝️', name: 'old key' },
            { emoji: '🔒', name: 'locked' },
            { emoji: '🔓', name: 'unlocked' },
            { emoji: '🔏', name: 'locked with pen' },
            { emoji: '🔐', name: 'locked with key' },
            { emoji: '✉️', name: 'envelope' },
            { emoji: '📦', name: 'package' },
            { emoji: '📫', name: 'closed mailbox with raised flag' },
            { emoji: '📜', name: 'scroll' },
            { emoji: '📄', name: 'page facing up' },
            { emoji: '📑', name: 'bookmark tabs' },
            { emoji: '📊', name: 'bar chart' },
            { emoji: '📈', name: 'chart increasing' },
            { emoji: '📉', name: 'chart decreasing' },
            { emoji: '📁', name: 'file folder' },
            { emoji: '📂', name: 'open file folder' },
            { emoji: '🗂️', name: 'card index dividers' },
            { emoji: '📅', name: 'calendar' },
            { emoji: '📌', name: 'pushpin' },
            { emoji: '📍', name: 'round pushpin' },
            { emoji: '📎', name: 'paperclip' },
            { emoji: '🖇️', name: 'linked paperclips' },
            { emoji: '📏', name: 'straight ruler' },
            { emoji: '📐', name: 'triangular ruler' },
            { emoji: '✂️', name: 'scissors' },
            { emoji: '🗃️', name: 'card file box' },
            { emoji: '🗄️', name: 'file cabinet' },
            { emoji: '🗑️', name: 'wastebasket' },
            { emoji: '🔒', name: 'lock' },
            { emoji: '🔓', name: 'unlock' },
            { emoji: '🔔', name: 'bell' },
            { emoji: '🔕', name: 'bell with slash' },
            { emoji: '📢', name: 'loudspeaker' },
            { emoji: '📣', name: 'megaphone' },
            { emoji: '🔍', name: 'magnifying glass tilted left' },
            { emoji: '🔎', name: 'magnifying glass tilted right' },
            { emoji: '🏷️', name: 'label' },
            { emoji: '🔖', name: 'bookmark' },
            { emoji: '🔗', name: 'link' },
            { emoji: '⭐', name: 'star' },
            { emoji: '🌟', name: 'glowing star' },
            { emoji: '⚡', name: 'high voltage' },
            { emoji: '☀️', name: 'sun' },
            { emoji: '🌙', name: 'crescent moon' },
            { emoji: '🌈', name: 'rainbow' },
            { emoji: '☁️', name: 'cloud' },
            { emoji: '🌧️', name: 'cloud with rain' },
            { emoji: '❄️', name: 'snowflake' },
            { emoji: '💧', name: 'droplet' },
            { emoji: '🌊', name: 'water wave' },
            { emoji: '⚠️', name: 'warning' },
            { emoji: '🚫', name: 'prohibited' },
            { emoji: '✅', name: 'check mark button' },
            { emoji: '✔️', name: 'check mark' },
            { emoji: '❌', name: 'cross mark' },
            { emoji: '❎', name: 'cross mark button' },
            { emoji: '❓', name: 'red question mark' },
            { emoji: '❗', name: 'red exclamation mark' },
            { emoji: '🔘', name: 'radio button' },
            { emoji: '🏁', name: 'chequered flag' },
            { emoji: '🚩', name: 'triangular flag' },
            { emoji: '🏳️', name: 'white flag' },
            { emoji: '🏴', name: 'black flag' },
            { emoji: '🌐', name: 'globe with meridians' },
        ],
    },
];

export function EmojiPicker({
    onSelect,
    onClose,
}: {
    onSelect: (emoji: string) => void;
    onClose: () => void;
}) {
    const [search, setSearch] = useState('');
    const [activeTab, setActiveTab] = useState(0);
    const containerRef = useRef<HTMLDivElement>(null);

    // Close on click outside
    useEffect(() => {
        function handleClickOutside(e: MouseEvent) {
            if (
                containerRef.current &&
                !containerRef.current.contains(e.target as Node)
            ) {
                onClose();
            }
        }

        document.addEventListener('mousedown', handleClickOutside);

        return () =>
            document.removeEventListener('mousedown', handleClickOutside);
    }, [onClose]);

    // Filter emojis based on search
    const searchResults = useMemo(() => {
        const query = search.toLowerCase().trim();

        if (!query) {
return null;
}

        const results: { emoji: string; name: string }[] = [];

        for (const cat of EMOJI_CATEGORIES) {
            for (const item of cat.emojis) {
                if (item.name.toLowerCase().includes(query)) {
                    results.push(item);
                }
            }
        }

        return results;
    }, [search]);

    return (
        <div
            ref={containerRef}
            className="absolute bottom-full right-0 z-[100] mb-3.5 flex h-[340px] w-72 flex-col rounded-2xl border border-[rgba(34,197,94,0.45)] bg-white shadow-[0_12px_40px_-5px_rgba(0,0,0,0.35)] backdrop-blur-xl dark:border-[rgba(34,197,94,0.6)] dark:bg-[#15342a] sm:w-[320px]"
            style={{
                boxShadow: '0 12px 35px -5px rgba(34,197,94,0.35)',
            }}
        >
            {/* Dialogue bubble tail pointing at the smiley icon */}
            <div className="absolute -bottom-2 right-[18px] z-10 h-4 w-4 rotate-45 border-r border-b border-[rgba(34,197,94,0.45)] bg-white dark:border-[rgba(34,197,94,0.6)] dark:bg-[#15342a]" />

            {/* Header / Search */}
            <div className="flex items-center gap-2 border-b border-[rgba(34,197,94,0.25)] p-2.5">
                <div className="relative flex-1">
                    <Search
                        size={14}
                        className="absolute top-1/2 left-2.5 -translate-y-1/2 text-muted-foreground"
                    />
                    <input
                        type="text"
                        value={search}
                        onChange={(e) => setSearch(e.target.value)}
                        placeholder="Search hundreds of emojis..."
                        autoFocus
                        className="w-full rounded-lg border border-black/10 bg-black/5 py-1.5 pr-2.5 pl-8 text-xs text-foreground outline-none placeholder:text-muted-foreground focus:border-able-green dark:border-white/10 dark:bg-black/20"
                    />
                </div>
                <button
                    type="button"
                    onClick={onClose}
                    aria-label="Close emoji picker"
                    className="rounded-lg p-1.5 text-muted-foreground transition-colors hover:bg-black/5 hover:text-foreground dark:hover:bg-white/10"
                >
                    <X size={15} />
                </button>
            </div>

            {/* Category tabs */}
            {!searchResults && (
                <div className="flex border-b border-[rgba(34,197,94,0.2)] px-2 py-1">
                    {EMOJI_CATEGORIES.map((cat, idx) => (
                        <button
                            key={cat.name}
                            type="button"
                            onClick={() => setActiveTab(idx)}
                            title={cat.name}
                            className={`flex flex-1 items-center justify-center rounded-lg py-1.5 text-base transition-colors ${
                                activeTab === idx
                                    ? 'bg-able-green/20 text-able-green'
                                    : 'text-muted-foreground hover:bg-black/5 hover:text-foreground dark:hover:bg-white/5'
                            }`}
                        >
                            {cat.icon}
                        </button>
                    ))}
                </div>
            )}

            {/* Emoji Grid */}
            <div className="flex-1 overflow-y-auto p-2.5 [scrollbar-gutter:stable]">
                {searchResults ? (
                    searchResults.length === 0 ? (
                        <p className="py-12 text-center text-xs text-muted-foreground">
                            No emojis found for "{search}"
                        </p>
                    ) : (
                        <div className="grid grid-cols-7 gap-1 sm:grid-cols-8">
                            {searchResults.map((item, i) => (
                                <button
                                    key={`${item.emoji}-${i}`}
                                    type="button"
                                    onClick={() => onSelect(item.emoji)}
                                    title={item.name}
                                    className="flex h-8 w-8 items-center justify-center rounded-lg text-xl transition-transform hover:scale-125 hover:bg-white/30 dark:hover:bg-white/10"
                                >
                                    {item.emoji}
                                </button>
                            ))}
                        </div>
                    )
                ) : (
                    <div>
                        <div className="mb-2 px-1 text-[0.68rem] font-semibold tracking-wider text-muted-foreground uppercase">
                            {EMOJI_CATEGORIES[activeTab].name} ({EMOJI_CATEGORIES[activeTab].emojis.length})
                        </div>
                        <div className="grid grid-cols-7 gap-1 sm:grid-cols-8">
                            {EMOJI_CATEGORIES[activeTab].emojis.map((item) => (
                                <button
                                    key={item.emoji}
                                    type="button"
                                    onClick={() => onSelect(item.emoji)}
                                    title={item.name}
                                    className="flex h-8 w-8 items-center justify-center rounded-lg text-xl transition-transform hover:scale-125 hover:bg-white/30 dark:hover:bg-white/10"
                                >
                                    {item.emoji}
                                </button>
                            ))}
                        </div>
                    </div>
                )}
            </div>
        </div>
    );
}
